export const FETCH_POKEMONS = "FETCH_POKEMONS";
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_ERROR = "FETCH_POKEMONS_ERROR";

export const FETCH_POKEMON_BY_NAME = "FETCH_POKEMON_BY_NAME";
export const FETCH_POKEMON_BY_NAME_SUCCESS = "FETCH_POKEMON_BY_NAME_SUCCESS";
export const FETCH_POKEMON_BY_NAME_ERROR = "FETCH_POKEMON_BY_NAME_ERROR";
